name: Build Project Infinity X for marble

on:
  workflow_dispatch:

jobs:
  build:
    uses: azwhikaru/ROM-Builders/.github/workflows/android.yml@master
    with:
      rom_name: ProjectInfinityX
      manifest_url: https://github.com/ProjectInfinity-X/manifest.git
      manifest_branch: 14
      device: marble
      dt_url: https://github.com/ProjectBlaze-Devices/device_xiaomi_marble.git
      dt_branch: 14
      vt_url: https://github.com/ProjectInfinity-X/vendor_infinity.git
      vt_branch: 14
      kt_url: https://github.com/LineageOS/android_kernel_xiaomi_sm7475.git
      kt_branch: lineage-20
      sync: true
      buildtype: unofficial
