name: Build Infinity X for Poco F5 (marble)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk git wget curl unzip python-is-python3 rsync bc bison flex zip gcc-multilib g++-multilib libncurses5 libncurses5-dev libssl-dev repo

    - name: Set up repo and manifest
      run: |
        mkdir infinity && cd infinity
        git config --global user.name "InfinityBuilder"
        git config --global user.email "builder@example.com"

        repo init --no-repo-verify --git-lfs -u https://github.com/ProjectInfinity-X/manifest -b 16 -g default,-mips,-darwin,-notdefault
        mkdir -p .repo/local_manifests

        cat > .repo/local_manifests/marble.xml <<EOF
<manifest>
  <project name="Evolution-X-Devices/device_xiaomi_marble" path="device/xiaomi/marble" remote="github" revision="infinity" />
  <project name="autoandroida/vendor_xiaomi_marble" path="vendor/xiaomi/marble" remote="github" revision="infinity" />
  <project name="Evolution-XYZ-Devices/device_xiaomi_marble-kernel" path="kernel/xiaomi/marble" remote="github" revision="infinity" />
</manifest>
EOF

    - name: Sync source
      run: |
        cd infinity
        repo sync -c --no-clone-bundle --no-tags --force-sync -j$(nproc)

    - name: Setup build environment
      run: |
        cd infinity
        source build/envsetup.sh
        lunch infinity_marble-userdebug

    - name: Build the ROM
      run: |
        cd infinity
        mka bacon -j$(nproc)

    - name: Upload ROM to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: InfinityX-marble
        path: infinity/out/target/product/marble/*.zip
